# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /client

# Installing dependencies
COPY ./package*.json /client


RUN npm install


# Start server on port 8080
EXPOSE 8000

CMD [ "npm","start" ]


